app = "clay-closekit"
primary_region = "iad"

[build]

[env]
  FLASK_APP = "run.py"

[deploy]
  release_command = "python migrate.py"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
