"""initial

Revision ID: 152cba7437a4
Revises: 
Create Date: 2026-02-25 22:42:46.604391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152cba7437a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('close_user_id', sa.String(length=100), nullable=False),
    sa.Column('close_org_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('close_user_id')
    )
    op.create_table('syncs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('close_query', sa.JSON(), nullable=False),
    sa.Column('clay_webhook_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('synced_records', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('close_record_id', sa.String(length=100), nullable=False),
    sa.Column('record_data', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sync_id'], ['syncs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sync_id', 'close_record_id', name='uq_sync_close_record')
    )
    with op.batch_alter_table('sync_records', schema=None) as batch_op:
        batch_op.create_index('ix_sync_records_close_record_id', ['close_record_id'], unique=False)
        batch_op.create_index('ix_sync_records_sync_id', ['sync_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_records', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_records_sync_id')
        batch_op.drop_index('ix_sync_records_close_record_id')

    op.drop_table('sync_records')
    op.drop_table('syncs')
    op.drop_table('users')
    # ### end Alembic commands ###
