"""add last_visited_at and sync_events

Revision ID: 15f3d0191689
Revises: 152cba7437a4
Create Date: 2026-03-02 21:22:28.463798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f3d0191689'
down_revision = '152cba7437a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('records_added', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_removed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sync_id'], ['syncs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_events', schema=None) as batch_op:
        batch_op.create_index('ix_sync_events_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_sync_events_sync_id', ['sync_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_visited_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_visited_at')

    with op.batch_alter_table('sync_events', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_events_sync_id')
        batch_op.drop_index('ix_sync_events_created_at')

    op.drop_table('sync_events')
    # ### end Alembic commands ###
